### ISSUE TITLE
Crash: Photoattacher Zooming Out to Finish ImageActivity

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#120]
It happens seldomly but sometimes the app crashes when zooming `ImageActivity` out. The activity is closed with the following exception: http://crashes.to/s/37a8f11ff89

    java.lang.IllegalStateException: The ImageView's ScaleType has been changed since attaching a PhotoViewAttacher
       at uk.co.senab.photoview.PhotoViewAttacher.checkImageViewScaleType(PhotoViewAttacher.java:707)
       at uk.co.senab.photoview.PhotoViewAttacher.setImageViewMatrix(PhotoViewAttacher.java:821)
       at uk.co.senab.photoview.PhotoViewAttacher.checkAndDisplayMatrix(PhotoViewAttacher.java:694)
       at uk.co.senab.photoview.PhotoViewAttacher.access$200(PhotoViewAttacher.java:47)
       at uk.co.senab.photoview.PhotoViewAttacher$AnimatedZoomRunnable.run(PhotoViewAttacher.java:999)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:549)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

I guess I just need to catch it in the right place and do nothing. Sadly, it's hard to reproduce.

**Comment by eugenkiss** [comment]
I tried various approaches but couldn't eliminate the problem. See also: https://github.com/chrisbanes/PhotoView/issues/229

**Comment by jjhesk** [comment]
I think I just got the same problem as well. 
I have discussed that in [here](https://github.com/r0adkll/Slidr/issues/12)

**Comment by AizazAZ** [comment]
package com.natgeo.widget;

import android.content.Context;
import android.support.v4.view.ViewPager;
import android.util.AttributeSet;
import android.view.MotionEvent;

/**
 * Created by AZ 
 */
public class PhotoViewViewPager extends ViewPager {

    public PhotoViewViewPager(Context context) {
        super(context);
    }

    public PhotoViewViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }


    //hack for zoom out exception
    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        try {
            return super.onInterceptTouchEvent(ev);
        } catch (IllegalArgumentException e) {
        } catch (ArrayIndexOutOfBoundsException e) {

        }
        return false;
    }
}

Replace <com.android.support.v4.view.ViewPager with this
