### ISSUE TITLE
Crash: DebugSettings onClick Release Version

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#137]
Doesn't make sense to me because the DebugSettings entry is hidden in the release Version but here's the exception: http://crashes.to/s/26666a5dd20

    java.lang.NullPointerException
       at android.content.ComponentName.<init>(ComponentName.java:78)
       at android.content.Intent.<init>(Intent.java:3836)
       at anabolicandroids.chanobol.ui.UiActivity.onDebugSettings(UiActivity.java:225)
       at anabolicandroids.chanobol.ui.UiActivity$$ViewInjector$2.doClick(UiActivity$$ViewInjector.java:37)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:4647)
       at android.view.ViewRootImpl.performClickHelper(ViewRootImpl.java:910)
       at android.view.ViewRootImpl.performClick(ViewRootImpl.java:919)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3385)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)

Might just need to put an Optional Butterknife annotation somewhere.

**Comment by egor-n** [comment]
I don't think this solves the issue.

From `ComponentName`'s [source](http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-0/android/content/ComponentName.java#76):
```java
public ComponentName(Context pkg, Class<?> cls) {
    mPackage = pkg.getPackageName();
    mClass = cls.getName(); // <-- line 78
}
```

So `@Named("DebugSettings") Class debugSettingsClass` is null (as it [should](https://github.com/eugenkiss/chanobol/blob/c91f7c74f3151074bd2922955559292179d9dc8c/src/main/java/anabolicandroids/chanobol/AppModule.java#L105)). I guess, the solution is to check for null, although it's kinda' dirty.

Weird thing, `debugSettings` entry is supposed to be gone, so an ordinary user shouldn't be able to click it. Do you think this issue has something in common with [this post](http://www.reddit.com/r/androiddev/comments/2yjmml/weird_google_bot_is_going_through_and_testing_old/) on Reddit?

**Comment by eugenkiss** [comment]
Thanks for your input.

> Weird thing, debugSettings entry is supposed to be gone, so an ordinary user shouldn't be able to click it. Do you think this issue has something in common with this post on Reddit?

That's a very good pointer. This really could be the case. I already wondered why I still get so relatively many crashes from version 1.3.0 although 1.3.1 is already released for quite some time. Of course, it could be that user's simply didn't update. But the weirdness of this crash hints at a bot. Maybe it send touch events so early in the activity lifecycle that the view hierarchy was not properly initialized yet or something. I don't know but I guess the crash is an anomaly. I'm going to push a "proper" fix anyway like you suggested.
