### ISSUE TITLE
Image Saving Broadcast Bug

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#160]
http://crashes.to/s/225c9ed53e0

java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=anabolicandroids.chanobol.reallysfw (has extras) } in anabolicandroids.chanobol.util.ImageSaver$6@42efd008
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: anabolicandroids.chanobol.util.ImageSaver$6@42efd008
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:667)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1743)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:475)
       at anabolicandroids.chanobol.util.ImageSaver$6.onReceive(ImageSaver.java:214)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by eugenkiss** [comment]
http://crashes.to/s/ec8e3f6d028
