### ISSUE TITLE
'Open External' for Image does not work on 2.3.3

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#55]
Is crash

    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://i.4cdn.org/a/1421433470129.jpg typ=image/* }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1409)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1379)
       at android.app.Activity.startActivityForResult(Activity.java:2827)
       at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:826)
       at android.support.v4.app.Fragment.startActivity(Fragment.java:896)
       at anabolicandroids.chanobol.ui.images.ImagesFragment.onOptionsItemSelected(ImagesFragment.java:85)
       at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1894)
       at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2034)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:356)
       at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
       at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
       at android.support.v7.widget.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:44)
       at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:77)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:163)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:738)
       at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
       at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
       at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)
       at android.widget.AdapterView.performItemClick(AdapterView.java:284)
       at android.widget.ListView.performItemClick(ListView.java:3513)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:1812)
       at android.os.Handler.handleCallback(Handler.java:587)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by eugenkiss** [comment]
This one's the culprit in `styles.xml`: `<item name="android:background">?android:selectableItemBackground</item>`

**Comment by eugenkiss** [comment]
See http://stackoverflow.com/questions/19714682/android-apply-selectableitembackground-in-xml-with-support-v7/19780767#19780767

**Comment by eugenkiss** [comment]
See http://stackoverflow.com/questions/11073832/no-activity-found-to-handle-intent
