### ISSUE TITLE
?android: stuff not accepted by 2.3.3

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#56]
Using these attributes in 'styles.xml' makes boom. This one is right: http://stackoverflow.com/a/15277821/283607

Also this: http://stackoverflow.com/questions/18278386/resource-cannot-be-found-no-identifier-for-missing-item

http://stackoverflow.com/questions/18152779/app-crashes-on-startup-on-android-api-10-but-not-on-api-16-because-of-resources

    java.lang.RuntimeException: Unable to start activity ComponentInfo{anabolicandroids.chanobol.dev/anabolicandroids.chanobol.ui.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.TextView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
       at android.app.ActivityThread.access$1500(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class android.widget.TextView
       at android.view.LayoutInflater.createView(LayoutInflater.java:518)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:707)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:619)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
       at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
       at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
       at anabolicandroids.chanobol.BaseActivity.onCreate(BaseActivity.java:25)
       at anabolicandroids.chanobol.ui.MainActivity.onCreate(MainActivity.java:84)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
       at android.app.ActivityThread.access$1500(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
       at android.view.LayoutInflater.createView(LayoutInflater.java:505)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:707)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:619)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
       at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
       at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
       at anabolicandroids.chanobol.BaseActivity.onCreate(BaseActivity.java:25)
       at anabolicandroids.chanobol.ui.MainActivity.onCreate(MainActivity.java:84)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
       at android.app.ActivityThread.access$1500(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x101030e a=2}
       at android.content.res.Resources.loadDrawable(Resources.java:1681)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.view.View.<init>(View.java:1951)
       at android.widget.TextView.<init>(TextView.java:344)
       at android.widget.TextView.<init>(TextView.java:337)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
       at android.view.LayoutInflater.createView(LayoutInflater.java:505)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:707)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:619)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
       at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
       at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
       at anabolicandroids.chanobol.BaseActivity.onCreate(BaseActivity.java:25)
       at anabolicandroids.chanobol.ui.MainActivity.onCreate(MainActivity.java:84)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
       at android.app.ActivityThread.access$1500(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:3683)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by eugenkiss** [comment]
This one's the culprit in `styles.xml`: `<item name="android:background">?android:selectableItemBackground</item>`

See for more information: http://stackoverflow.com/questions/19714682/android-apply-selectableitembackground-in-xml-with-support-v7/19780767#19780767
