### ISSUE TITLE
Incorrect Transformation of Anchor Tags in Post Text

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#59]
Plaintext URLs are correctly transformed into clickable links in the text body of a post's cardview. However, anchor tags that themself contain a plaintext URL as the `href` attribute break. This is not a big problem as, apparently, such anchor tags can only appear in sticky posts. Still, it's an unpleasent flaw. See the relevant code here: https://github.com/eugenkiss/chanobol/blob/84a61cf517969a240b617827fd1c74ea1c3b3320/src/main/java/anabolicandroids/chanobol/ui/posts/PostView.java#L129

Chanu does the transformation correctly. So a good strategy is to study [Chanu's source code](https://github.com/grzegorznittner/chanu) to find out how they parse, transform and display links in posts. Or [Clover's Source Code](https://github.com/Floens/Clover/)

See also #3.

**Comment by eugenkiss** [comment]
See also this gist: https://gist.github.com/eugenkiss/93a8e20c85ca97a8ce47#file-thread-problem-json-L63

`<a href=\"/fit/thread/30466611#p30466611\` leads to the following exception:

    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/fit/thread/30466611 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
       at android.app.Activity.startActivityForResult(Activity.java:3736)
       at android.app.Activity.startActivityForResult(Activity.java:3697)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
       at android.app.Activity.startActivity(Activity.java:4007)
       at android.app.Activity.startActivity(Activity.java:3975)
       at android.text.style.URLSpan.onClick(URLSpan.java:62)
       at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
       at android.widget.TextView.onTouchEvent(TextView.java:7969)
       at android.view.View.dispatchTouchEvent(View.java:8388)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
       at android.view.View.dispatchPointerEvent(View.java:8578)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5675)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5646)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5791)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by eugenkiss** [comment]
This might help, too: http://developer.android.com/samples/TextLinkify/index.html

**Comment by eugenkiss** [comment]
Related crashes:

- http://crashes.to/s/3af38ca47a0
- http://crashes.to/s/476b28037fa
- http://crashes.to/s/e99bf3dd344
- http://crashes.to/s/638890bcf03
- http://crashes.to/s/e99bf3dd344

**Comment by eugenkiss** [comment]
Good progress is being made here. Everything works now even links to other threads which previously crashed the application. Need to tidy/restructure the code though which is going to take some time.
