### ISSUE TITLE
Nullpointerexception on Return to App

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#65]
I suspect very strongly that this is the culprit for #44.

    java.lang.NullPointerException: Attempt to read from field 'java.lang.String anabolicandroids.chanobol.api.data.Common.id' on a null object reference
       at anabolicandroids.chanobol.ui.posts.PostView.initText(PostView.java:109)
       at anabolicandroids.chanobol.ui.posts.PostView.bindTo(PostView.java:203)
       at anabolicandroids.chanobol.ui.posts.PostsFragment$PostsAdapter.bindView(PostsFragment.java:280)
       at anabolicandroids.chanobol.ui.posts.PostsFragment$PostsAdapter.bindView(PostsFragment.java:258)
       at anabolicandroids.chanobol.BindableAdapter.getView(BindableAdapter.java:29)
       at android.widget.AbsListView.obtainView(AbsListView.java:2344)
       at android.widget.ListView.makeAndAddView(ListView.java:1864)
       at android.widget.ListView.fillSpecific(ListView.java:1344)
       at android.widget.ListView.layoutChildren(ListView.java:1651)
       at android.widget.AbsListView.onLayout(AbsListView.java:2148)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:890)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.view.View.layout(View.java:15596)
       at android.view.ViewGroup.layout(ViewGroup.java:4966)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by eugenkiss** [comment]
The root of the problem must have something to do with acivity/fragment lifecycles and stuff being reinitialized but the adapter or something else having a stale reference even though the fragment is set to retain its instance. I don't have implemented logic wrt configuration changes yet, i.e. fragments saving and restoring their state correctly, to not waste too much time in the beginning on correctness on stuff (classes/fragments/activities) that might be ditched anyway.

But it seems to be impossible to reproduce this bug reliably. Without this reproduction ability it's all guessing anyway. So the "fix" of this problem that I pushed is symptomatic to at least not have the application crash.
