### ISSUE TITLE
Use Different Drawable Sizes

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#73]
Currently there's only one big resolution in `drawables`.

**Comment by eugenkiss** [comment]
This already lead to the following exception in a VM:

    java.lang.OutOfMemoryError: bitmap size exceeds VM budget
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
            at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
            at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:498)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:473)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:336)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:697)
            at android.content.res.Resources.loadDrawable(Resources.java:1709)
            at android.content.res.Resources.getDrawable(Resources.java:581)
            at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
            at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:122)
            at android.support.v7.internal.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:422)
            at android.support.v7.internal.view.menu.ListMenuItemView.initialize(ListMenuItemView.java:107)
            at android.support.v7.internal.view.menu.MenuPopupHelper$MenuAdapter.getView(MenuPopupHelper.java:377)
            at android.support.v7.internal.view.menu.MenuPopupHelper.measureContentWidth(MenuPopupHelper.java:219)
            at android.support.v7.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:153)
            at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:752)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by eugenkiss** [comment]
I'm pretty sure I read somewhere that having e.g. xxhdpi and hdpi is enough as the Android OS will scale the assets appropriately for other densities...

**Comment by eugenkiss** [comment]
Well, I think xxhdpi + automatic scaling by Android OS is good enough.
