### ISSUE TITLE
Crash: Nullpointer Board.name

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#77]
From Crashlytics. Must have something to do with state recreation I assume.

http://crashes.to/s/b735699e8c6

    java.lang.RuntimeException: Unable to start activity ComponentInfo{anabolicandroids.chanobol.sfw/anabolicandroids.chanobol.ui.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String anabolicandroids.chanobol.api.data.Board.name' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String anabolicandroids.chanobol.api.data.Board.name' on a null object reference
       at anabolicandroids.chanobol.ui.threads.ThreadsFragment.load(ThreadsFragment.java:147)
       at anabolicandroids.chanobol.ui.threads.ThreadsFragment.onActivityCreated(ThreadsFragment.java:99)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:5949)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by eugenkiss** [comment]
Definitely related to #67. Setting `setRetainInstance` to true does not 100% prevent Android from recreating fragments. A quick fix would be to make `Board` parcelable and then but it in the bundle as described in #67.

Maybe a better approach is to use an approach like in http://corner.squareup.com/2014/10/advocating-against-android-fragments.html which should eliminate this problem altogether.
