### ISSUE TITLE
Crash: Gridlayout Index Out of Bounds

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#78]
http://crashes.to/s/19ebd09e62e

    java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:361)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1097)
       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:957)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:2797)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:543)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by eugenkiss** [comment]
Hmm, don't know where it comes from.

**Comment by eugenkiss** [comment]
https://code.google.com/p/android/issues/detail?id=93710
