### ISSUE TITLE
Crash: DeepZoom OutOfMemory

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#79]
Not much can be done from my side except improving Ion directly. I've actually encountered this bug a couple of times myself. http://crashes.to/s/d354bc8e97f

    java.lang.OutOfMemoryError
       at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:122)
       at com.koushikdutta.async.util.StreamUtility.readToEndAsArray(StreamUtility.java:57)
       at com.koushikdutta.ion.LoadDeepZoom$1.run(LoadDeepZoom.java:66)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by eugenkiss** [comment]
This one, too: http://crashes.to/s/a422ac402f6

    java.lang.OutOfMemoryError
       at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(BitmapRegionDecoder.java)
       at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:186)
       at com.koushikdutta.ion.LoadDeepZoom$1.run(LoadDeepZoom.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by eugenkiss** [comment]
I'll at least add a check in 1.3 such that deep zoom is only activated for images of 4000x4000 or something.
