### ISSUE TITLE
Crash: No Activity found to handle Intent

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#81]
Fresh from Crashlytics http://crashes.to/s/ae6e3068a99

It probably has to do with the post text parsing when there is a link that references another thread. Once it's improved this crash should be a thing of the past. See #3.

    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=/vr/thread/2192268 (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
       at android.app.Activity.startActivityForResult(Activity.java:3424)
       at android.app.Activity.startActivityForResult(Activity.java:3385)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
       at android.app.Activity.startActivity(Activity.java:3627)
       at android.app.Activity.startActivity(Activity.java:3595)
       at android.text.style.URLSpan.onClick(URLSpan.java:62)
       at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
       at android.widget.TextView.onTouchEvent(TextView.java:7713)
       at android.view.View.dispatchTouchEvent(View.java:7713)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2329)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2277)
       at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(XposedBridge.java)
       at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
       at android.view.View.dispatchPointerEvent(View.java:7893)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3950)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3829)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3445)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3414)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3521)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3422)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3578)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3445)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3414)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3422)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3395)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5535)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5515)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5486)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5615)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by eugenkiss** [comment]
Duplicate of #59
