### ISSUE TITLE
Crash: Gif OutOfMemory

### ISSUE THREAD

**Issue by eugenkiss** [eugenkiss/chanobol#84]
Probably nothing that can be done from my side outside of switching out Ion which I don't plan to. http://crashes.to/s/a95533cb0a9

    java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1001)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1025)
       at com.koushikdutta.ion.gif.GifDecoder.setPixels(GifDecoder.java:279)
       at com.koushikdutta.ion.gif.GifDecoder.readImage(GifDecoder.java:526)
       at com.koushikdutta.ion.gif.GifDecoder.nextFrame(GifDecoder.java:140)
       at com.koushikdutta.ion.IonDrawable$IonGifDecoder$1.run(IonDrawable.java:172)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by eugenkiss** [comment]
I think there is nothing (reasonably achievable) to be done from my side.
